apiVersion: v1
kind: Service
metadata:
  name: {{ include "craned.fullname" . }}
  labels:
    {{- include "craned.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
      name: bind
  selector:
    {{- include "craned.selectorLabels" . | nindent 4 }}
