apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
  labels:
    {{- include "metric-adapter.labels" . | nindent 4 }}
spec:
  service:
    name: {{ include "metric-adapter.fullname" . }}
    namespace: {{ .Release.Namespace }}
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta2.custom.metrics.k8s.io
  labels:
    {{- include "metric-adapter.labels" . | nindent 4 }}
spec:
  service:
    name: {{ include "metric-adapter.fullname" . }}
    namespace: {{ .Release.Namespace }}
  group: custom.metrics.k8s.io
  version: v1beta2
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 200