
service:
  enabled: true
  type: NodePort
  nodePort: 31112
  port: 80
  targetPort: 3000
  # targetPort: 4181 To be used with a proxy extraContainer
  annotations: {}
  labels: {}
  portName: service

# Administrator credentials when not using an existing secret (see below)
adminUser: admin
adminPassword: admin


## Configure grafana datasources
## ref: http://docs.grafana.org/administration/provisioning/#datasources
##
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.crane-system.svc.cluster.local
        access: proxy
        isDefault: true


dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
   default:
     cluster-costs:
       url: https://raw.githubusercontent.com/gocrane/helm-charts/main/integration/grafana/dashboards/cluster-costs.json
     costs-dimension:
       url: https://raw.githubusercontent.com/gocrane/helm-charts/main/integration/grafana/dashboards/costs-dimension.json
     namespace-costs:
       url: https://raw.githubusercontent.com/gocrane/helm-charts/main/integration/grafana/dashboards/namespace-costs.json
